#!/bin/sh

#chown -R root:root *
chmod 775 /customer/*.sh
chmod 775 /customer/cust_app_upgrade
chmod 777 /customer/config/
chmod 777 /cust/config/
touch /customer/config/error.txt
chmod 777 /customer/config/error.txt
chmod 777 /customer/config/smartreader-default.json
chown root:cap /customer/config/smartreader-default.json
chown root:cap /customer/config/error.txt
#chmod -R 777 /customer/config/*.ini
#chmod -R 777 /customer/config/*.json

rm -rf /customer/upgrading
#/opt/ys/rshell -c "config network https enable"
#/opt/ys/rshell -c "config rfid interface rest"

mkdir /customer/wwwroot/logs
chmod 777 /customer/wwwroot/logs
chmod 777 /customer/wwwroot/logs/log-app.txt
rm -rf /customer/wwwroot/logs/*.*
cd /customer


if [ ! -e /customer/config/smartreader.json ]; then                       
    cp /customer/config/smartreader-default.json /customer/config/smartreader.json
    chmod 777 /customer/config/smartreader.json
else
    chmod 777 /customer/config/smartreader.json
    chown cap:cap /customer/config/smartreader.json
fi

chmod 777 /customer/config/smartreader.json
chown cap:cap /customer/config/smartreader.json

#/usr/bin/systemctl start  wpa_supplicant-wired@eth0.service

sh /customer/monitor-upgrade.sh &
(( count = 1 ))
while true ; do
        # Count the log lines and clean if needed. 
	# $(..) can be used to get the output of a command
	# use -ge, not >, for comparing numbers
	# 5 != 50k
	#if [ "$(wc -l < /customer/wwwroot/logs/log-app.txt)" -ge 30000 ]
	#then
	#	rm -rf /customer/wwwroot/logs/log-app.txt  # specify the file to delete
	#	echo "++++++++" > /customer/wwwroot/logs/log-app.txt
		#echo "IS GREATER"
	#fi # end the if statement 
	# Check to see whether /customer/SmartReaderStandalone exists
        if [ -f /customer/SmartReaderStandalone ] ; then
                # The /customer/SmartReaderStandalone exists, so tes whether it's executable
                if [ -x /customer/SmartReaderStandalone ] ; then
                    if [ ! -e /customer/upgrading ]; then
                            # /customer/SmartReaderStandalone is executable, so run it
                            appDir=/customer
                            /customer/SmartReaderStandalone
                            /usr/bin/logger -p user.notice \
                                    "Starting custom application, count $count."
                            (( count = count + 1 ))
                    fi
                fi
                        # /customer/SmartReaderStandalone is NOT executable, so wait for a moment
                 
		sleep 2
        else
                exit 0
        fi
done
